# Generated by Django 2.1.7 on 2019-02-14 11:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(required=False)), ('link_external', wagtail.core.blocks.CharBlock(label='External link', required=False)), ('meta_id', wagtail.core.blocks.CharBlock(classname='wasm-meta-field', help_text='CTA Id', label='ID', required=False)), ('meta_cta_variant', wagtail.core.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], classname='wasm-meta-field', label='CTA Style'))])), ('grid', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False)), ('body', wagtail.core.blocks.StreamBlock([('rich_text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(required=False)), ('meta_id', wagtail.core.blocks.CharBlock(classname='wasm-meta-field', help_text='Rich Text Id', label='ID', required=False))]))], blank=True, null=True)), ('meta_id', wagtail.core.blocks.CharBlock(classname='wasm-meta-field', help_text='Grid Id', label='ID', required=False))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
