# Generated by Django 2.1.8 on 2019-05-01 11:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='body',
            field=wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(required=False)), ('link_external', wagtail.core.blocks.CharBlock(label='External link', required=False)), ('meta_id', wagtail.core.blocks.CharBlock(classname='wasm-meta-field', help_text='CTA Id', label='ID', required=False)), ('meta_cta_variant', wagtail.core.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], classname='wasm-meta-field', label='CTA Style')), ('link_with_variant', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(required=False)), ('meta_variant', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('variant1', 'Variant1'), ('variant2', 'Variant2')], classname='wasm-meta-field', label='Variant'))], label='Link', required=False))])), ('grid', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False)), ('body', wagtail.core.blocks.StreamBlock([('rich_text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(required=False)), ('meta_id', wagtail.core.blocks.CharBlock(classname='wasm-meta-field', help_text='Rich Text Id', label='ID', required=False))]))], blank=True, null=True)), ('meta_id', wagtail.core.blocks.CharBlock(classname='wasm-meta-field', help_text='Grid Id', label='ID', required=False))]))], blank=True, null=True),
        ),
    ]
